### ISSUE TITLE
Add more services? (SpeechToText Webhook)

### ISSUE THREAD

**Issue by hongkongkiwi** [fdmsantos/terraform-azurerm-api-connections#1]
I'd really like to add this: https://learn.microsoft.com/en-us/rest/api/speechtotext/web-hooks/create?view=rest-speechtotext-2024-05-15-preview&tabs=HTTP

Where could I get the JSON schema from?

**Comment by hongkongkiwi** [comment]
In this case, there's no bicep template for this service so the only choice is the HTTP API :/

**Comment by fdmsantos** [comment]
Hi,

Thanks for your support on this module.

The intend for this module is create api connections to work with Logic Apps.

The only api connection that i find related with speech to text is related with this connector: https://learn.microsoft.com/en-us/connectors/cognitiveservicesspe/

But i think isn't this you are looking for.

There is another connectors related with Cognitive/Azure Ai Services.

Could you provide more info about what you are trying to do, to check if this fit on this module? Are you creating or use a Logic App?

I get the JSON Schema from Export Template option after the Api connection creation on Azure.

**Comment by hongkongkiwi** [comment]
Ah I see, I may have misunderstood the purpose of this module. Thanks for clarifying.

What I'm trying to do is simply create a SpeechToText Webhook somehow using Terraform. It only exists in the Azure HTTP api I linked above, but it doesn't appear in any other places (such as the Bicep or ARM api).

I'd like to manage this using Terraform as it's something you create once and terraform should manage it. But apart from calling the rest api I hadn't figured out another solution to do this from terraform (hence why I'm hunting down modules).

**Comment by fdmsantos** [comment]
Try Create the webhook manually. Then in resource go to Automation Menu and
check if exists Export Template option.
